; If you have plugins installed like DebugKit
DebugKit.Dashboard = *
DebugKit.Requests = *
DebugKit.Panels = *

Users = login

Pages = view

PostCategories = view

Posts = index, view

Services = view

SystemicPages = display, robots, sitemap
